POST http://localhost:3001/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
GET http://localhost:3001/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc4ODY2ODY5fQ.1HnIulImCKkji_K_RpEMGvFOJmt-seYNWGGcExA2bwI


###
GET http://localhost:3001/states/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc4ODY2ODY5fQ.1HnIulImCKkji_K_RpEMGvFOJmt-seYNWGGcExA2bwI


###
POST http://localhost:3001/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc4ODY2ODY5fQ.1HnIulImCKkji_K_RpEMGvFOJmt-seYNWGGcExA2bwI
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3001/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc4ODY2ODY5fQ.1HnIulImCKkji_K_RpEMGvFOJmt-seYNWGGcExA2bwI


###
DELETE http://localhost:3001/districts/32/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc4ODY2ODY5fQ.1HnIulImCKkji_K_RpEMGvFOJmt-seYNWGGcExA2bwI


###
PUT http://localhost:3001/districts/12/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc4ODY2ODY5fQ.1HnIulImCKkji_K_RpEMGvFOJmt-seYNWGGcExA2bwI
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3001/states/6/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjc4ODY2ODY5fQ.1HnIulImCKkji_K_RpEMGvFOJmt-seYNWGGcExA2bwI

